spring:
  application:
    name: shop-management-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  file:
    name: logs/shop-management-service.log

management:
  endpoint:
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,logfile
